name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements-dev.txt

      - name: Train (tagged version)
        run: python -m ml.train --seed 42 --output-dir artifacts --version "${GITHUB_REF_NAME}"

      - name: Bake artifacts into app/
        run: |
          mkdir -p app/model
          cp artifacts/pipeline.pkl app/model/
          cp artifacts/feature_names.json app/model/
          cp artifacts/MODEL_VERSION app/model/

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE_LOWER=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker build -t "$IMAGE_LOWER" .
          echo "IMAGE_LOWER=$IMAGE_LOWER" >> $GITHUB_ENV

      - name: Smoke test container
        run: |
          set -euo pipefail
          cid="$(docker run -d -p 8080:8080 "$IMAGE_LOWER")"
          trap 'echo "--- logs ---"; docker logs "$cid" || true; docker rm -f "$cid" >/dev/null 2>&1 || true' EXIT
          for i in $(seq 1 30); do
            curl --fail -sS --no-progress-meter http://localhost:8080/ready >/dev/null && break
            sleep 1
          done
          curl --fail -sS --no-progress-meter http://localhost:8080/health | jq .
          curl --fail -sS --no-progress-meter -H "Content-Type: application/json" \
            -d '{"age":0.02,"sex":-0.044,"bmi":0.06,"bp":-0.03,"s1":-0.02,"s2":0.03,"s3":-0.02,"s4":0.02,"s5":0.02,"s6":-0.001}' \
            http://localhost:8080/predict | jq .

      - name: Push image
        run: docker push "$IMAGE_LOWER"

      - uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: artifacts/metrics.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Release for ${{ github.ref_name }}. Metrics attached as artifacts/metrics.json.
          files: |
            artifacts/metrics.json
